DROP TABLE IF EXISTS user;
--DROP TABLE IF EXISTS post;
DROP TABLE IF EXIST query;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

--CREATE TABLE post (
--  id INTEGER PRIMARY KEY AUTOINCREMENT,
--  author_id INTEGER NOT NULL,
--  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--  title TEXT NOT NULL,
--  body TEXT NOT NULL,
--  FOREIGN KEY (author_id) REFERENCES user (id)
--);

--CREATE TABLE query{
--    username TEXT NOT NULL,
--    image_addr TEXT UNIQUE NOT NULL,
--    classification TEXT NOT NULL
--}